config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  get 'contacts/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {}

  root to: "pages#home"
  get "about", to: "pages#about"
  get "contact", to: "contacts#new"
  get "tac", to: "pages#tac"
  get "policies", to: "pages#policies"

  resources :contacts, only: [:new, :create]
  get "blog", to: "pages#blog"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :dreamlogs do
    resources :dreams, only: [:new, :create, :index, :show]
  end

  resources :dreams, only: [:edit, :update, :destroy] do
    resources :interpretations, only: [:new, :create, :index, :show]
    get 'analyze', to: 'interpretations#analyze'
  end
  resources :interpretations, only: [:edit, :update, :destroy]
  resources :personal_details, only: [:create, :edit, :update, :destroy]

  get 'discuss', to: 'interpretations#discuss'
end

app/models/dreamlog.rb
class Dreamlog < ApplicationRecord
  belongs_to :user
  has_many :dreams, dependent: :destroy
end

app/controllers/dreamlogs_controller.rb
class DreamlogsController < ApplicationController
  def index
    @dreams = current_user.dreams.reject { |dream| dream.interpretations.empty? }
  end

  def show
    @dreamlog = Dreamlog.find(params[:id])
    @personal_detail = PersonalDetail.new
  end

  def new
    @dreamlog = Dreamlog.new
  end

  def create
    @dreamlog = Dreamlog.new
    @dreamlog.user = current_user
    if @dreamlog.save
      redirect_to dreamlog_path(@dreamlog)
    else
      render :new
    end
  end

  private

  def dreamlog_params
    params.require(:dreamlog).permit
  end
end

app/views/dreamlogs/index.html.erb
<div class="banner">
  <h1>The DreamVault</h1>
  <p>
    The DreamVault is an innovative repository where users can store and manage their interpreted dreams using the advanced AI technology called Onirix. It is a secure and intuitive platform designed to help users keep track of their dream interpretations over time, and gain insights into their subconscious thoughts and emotions.
  </p>
  <br>
  <p>
    You have <strong><%= pluralize(@dreams.count, 'dream') %></strong> in your DreamVault.
  </p>
</div>

<div class="dreams">
  <% @dreams.each do |dream| %>
    <div class="dream">
      <h2>Dream analysed on: <%= dream.created_at.strftime("%d/%m/%Y at %H:%M") %>
      </h2>
      <p>The main character of your dream: <%= dream.maincharacter %></p>
      <p>The main emotion of your dream: <%= dream.emotion %></p>
      <p>The type of action in your dream: <%= dream.action %></p>
      <p>The location of your dream: <%= dream.location %></p>
      <% unless dream.description.blank? %>
        <p>A small description of your dream: <%= dream.description %></p>
      <% end %>

      <h3>The Interpretation of your dream</h3>
      <% dream.interpretations.each do |interpretation| %>
        <p><%= interpretation.description %></p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/dreamlogs/new.html.erb
<div class="dream-log-container">
<h1>Hello, I am Onirix aka the Dream Oracle
</h1>

<p>
  Through a series of questions, tell Onirix about yourself and your dream (those you remember, at least!). It will help get a clearer understanding of your subconscious mind and help you unlock the secrets of our dream !

  Please do not rush while answering the questions.
</p>

<%= simple_form_for @dreamlog, data: {turbo: false} do |f| %>
      <%= f.submit "Let's begin", class: "btn secondary-cta-sign my-4" %>
  <% end %>

<div>
  <p>
    We guarantee to keep your information private. As you continue, you will accept the privacy policy, policy and the terms of conditions of Onirix.
  </p>
</div>
</div>

app/views/dreamlogs/show.html.erb
<div class="container personal-section"
  data-controller='toggle-form'
>
  <div class="step step-1 active"
    data-toggle-form-target='step1'
  >
  <%= simple_form_for(@personal_detail, url: personal_details_path(dreamlog_id: @dreamlog.id), data:{turbo: false}) do |f| %>
      <h2>Tell us more about yourself</h2>
      <p>What is your age?</p>
      <div class="choices">
        <%= f.collection_radio_buttons :age, [
          ["18-24", "18-24"],
          ["25-34", "25-34"],
          ["35-44", "35-44"],
          ["45-54", "45-54"],
          ["55+", "55+"]
        ], :second, :first, input_html: { class: "tag-selector" },
                    item_wrapper_class: 'tag-item' %>
      </div>
        <button class="btn secondary-cta-sign my-4" data-action='click->toggle-form#showStep2' >Next</button>
  </div>

    <div class="step step-2" data-toggle-form-target='step2'>
      <h2>Tell us more about yourself</h2>
      <p>What is your gender</p>
      <div class="choices vertical">
        <%= f.collection_radio_buttons :gender, [  ["Male", "Male"],
          ["Female", "Female"],
          ["LGBTQIA+", "LGBTQIA+"],
          ["I don't want to specify", "I don't want to specify"]
        ], :second, :first, input_html: { class: "tag-selector" },
                    item_wrapper_class: 'tag-item' %>
      </div>

      <button class="btn secondary-cta-sign my-4" data-action='click->toggle-form#showStep1'>Go Back</button>
      <button class="btn secondary-cta-sign my-4" data-action='click->toggle-form#showStep3'>Proceed</button>
    </div>
    <div class="step step-3" data-toggle-form-target='step3'>
      <h2>What is your current occupation?</h2>
      <div class="choices vertical">
        <%= f.collection_radio_buttons :occupation, [  ["Student", "Student"],
          ["Employed", "Employed"],
          ["Unemployed", "Unemployed"],
          ["House Work", "House Work"],
          ["Retired", "Retired"],
          ["Other", "Other"]
        ], :second, :first, input_html: { class: "tag-selector" },
                    item_wrapper_class: 'tag-item' %>
      </div>
      <button class="btn secondary-cta-sign my-4" data-action='click->toggle-form#showStep2' >Go Back</button>
      <button class="btn secondary-cta-sign my-4" data-action='click->toggle-form#showStep4'>Proceed</button>
    </div>

    <div class="step step-4" data-toggle-form-target='step4'>
      <h2>What is your current relationship status?</h2>
      <div class="choices vertical">
        <%= f.collection_radio_buttons :lovesituation, [  ["Single", "Single"],
          ["In a relationship", "In a relationship"],
          ["Married", "Married"],
          ["Divorced", "Divorced"],
          ["Widowed", "Widowed"],
          ["Happy with my cat", "Happy with my cat"],
          ["Other", "Other"]
        ], :second, :first, input_html: { class: "tag-selector" },
                      item_wrapper_class: 'tag-item' %>
      </div>
      <button class="btn secondary-cta-sign my-4" data-action='click->toggle-form#showStep3' >Go Back</button>
      <%= f.submit "Submit", class:"btn secondary-cta-sign my-4" %>
    </div>
    <% end %>

</div>