config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  get 'contacts/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {}

  root to: "pages#home"
  get "about", to: "pages#about"
  get "contact", to: "contacts#new"
  get "tac", to: "pages#tac"
  get "policies", to: "pages#policies"

  resources :contacts, only: [:new, :create]
  get "blog", to: "pages#blog"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :dreamlogs do
    resources :dreams, only: [:new, :create, :index, :show]
  end

  resources :dreams, only: [:edit, :update, :destroy] do
    resources :interpretations, only: [:new, :create, :index, :show]
    get 'analyze', to: 'interpretations#analyze'
  end
  resources :interpretations, only: [:edit, :update, :destroy]
  resources :personal_details, only: [:create, :edit, :update, :destroy]

  get 'discuss', to: 'interpretations#discuss'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <!-- Grid container -->
  <div class="container">
    <!-- Section: Links -->
    <section class="mt-5">
      <!-- Grid row-->
      <div class="footer-links row text-center d-flex justify-content-center pt-5">
        <!-- Grid column -->
        <div class="foot-link-item col-md-2 col-sm-12">
          <h6 class="text-uppercase font-weight-bold">
            <a href="#about-iid" class="text-white">About Us</a>
          </h6>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="foot-link-item col-md-2 col-sm-12">
          <h6 class="text-uppercase font-weight-bold">
            <a href="#about-onirix" class="text-white">Onirix AI</a>
          </h6>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="foot-link-item col-md-2 col-sm-12">
          <h6 class="text-uppercase font-weight-bold">
            <a href="#Dream" class="text-white">What is a Dream ?</a>
          </h6>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="foot-link-item col-md-2 col-sm-12">
          <h6 class="text-uppercase font-weight-bold">
            <%= link_to "Blog", "/blog", class: "text-white" %>
          </h6>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="foot-link-item col-md-2 col-sm-12">
          <h6 class="text-uppercase font-weight-bold">
            <%= link_to "Contact", "/contact", class: "text-white" %>
          </h6>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row-->
    </section>
    <!-- Section: Links -->

    <hr class="my-5" />

    <!-- Section: Social -->
    <section class="text-center mb-5">
      <a href="" class="text-white me-4">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="" class="text-white me-4">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="" class="text-white me-4">
        <i class="fab fa-google"></i>
      </a>
      <a href="" class="text-white me-4">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="" class="text-white me-4">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="" class="text-white me-4">
        <i class="fab fa-github"></i>
      </a>
    </section>
    <!-- Section: Social -->

    <!-- Copyright -->
    <div class="foot-bot text-center d-flex justify-content-between p-3">
      <p>Copyright &copy; 2023</p>
      <%= link_to "Terms & Conditions", "/tac", class: "text-white" %>
      <%= link_to "Privacy Policy", "/policies", class: "text-white" %>
      <h6>Made with <i class="fas fa-heart fa-beat"></i> by the Crazy Chicken Team 🐣</h6>
    </div>
    <!-- Copyright -->
  </div>
  <!-- Grid container -->
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-chicken">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "logo.svg" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
            <%= link_to "Home", "/", class: "nav-link" %>
        </li>
        <li class="nav-item active">
            <%= link_to "About", "#about", class: "nav-link" %>
        </li>
        <li class="nav-item active">
            <%= link_to "Blog", "/blog", class: "nav-link" %>
        </li>
        <li class="nav-item active">
            <%= link_to "Contact", "/contact", class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Analyze My Dream", new_dreamlog_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">

          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <% if current_user.avatar.attached? %>
            <%= cl_image_tag(current_user.avatar.key, :transformation=>[
                                                        {:gravity=>"face", :height=>400, :width=>400, :crop=>"crop",},
                                                        {:radius=>"max"},
                                                        {:width=>400, :crop=>"thumb"}],
                            class: "avatar") %>
          <% else %>
            <%= image_tag "logo.png", class: "avatar", alt: "dropdown menu" %>
          <% end %>

          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">

              <% if current_user.admin? %>
                <%= link_to "Admin Platform", '/admin', class: "dropdown-item" %>
              <% end %>
              <%= link_to "DreamVault", dreamlogs_path, class: "dropdown-item" %>
              <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link secondary-cta-sign" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link main-cta-color-BonWup" %>
          </li>
        <% end %>

      </ul>
    </div>
  </div>
</div>

app/views/shared/_reviews.html.erb
<section class="gradient-custom">
  <div class="my-5 py-5">
    <div class="row d-flex justify-content-center">
      <div class="col-md-12">
        <div class="card rounded-10">
          <div class="card-body px-4 py-5 rounded">
            <!-- Carousel wrapper -->
            <div id="carouselExampleControls" class="carousel carousel-dark slide" data-bs-ride="carousel">
              <div class="carousel-inner">
                <div class="carousel-item active">
                  <div class="row d-flex justify-content-center">
                    <div class="col-lg-10 col-xl-8">
                      <div class="row">
                        <div class="col-lg-4 d-flex justify-content-center">
                          <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(1).webp"
                            class="rounded-circle shadow-1 mb-4 mb-lg-0" alt="woman avatar" width="150"
                            height="150" />
                        </div>
                        <div
                          class="col-9 col-md-9 col-lg-7 col-xl-8 text-center text-lg-start text-black mx-auto mx-lg-0">
                          <h4 class="mb-4">Sam Rotherfield - 22 years old</h4>
                          <p class="mb-0 pb-3">
                            With Onirix, I was able to turn my dreams into a tool for self-discovery and personal growth.
                            The AI's analysis and predictions helped me better understand my own thought patterns and identify areas where I needed to focus my attention.
                            Thanks to Onirix, I feel more in control of my emotions in my relatinship than ever before.
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- Single item -->
                <div class="carousel-item">
                  <div class="row d-flex justify-content-center">
                    <div class="col-lg-10 col-xl-8">
                      <div class="row">
                        <div class="col-lg-4 d-flex justify-content-center">
                          <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(2).webp"
                            class="rounded-circle shadow-1 mb-4 mb-lg-0" alt="woman avatar" width="150"
                            height="150" />
                        </div>
                        <div
                          class="col-9 col-md-9 col-lg-7 col-xl-8 text-center text-lg-start text-black mx-auto mx-lg-0">
                          <h4 class="mb-4">Melina Golligath - 35 years old</h4>
                          <p class="mb-0 pb-3">
                            I've always been a bit skeptical of AI and machine learning, but Onirix blew me away.
                            The predictions it generated based on my dreams were spot-on, and they gave me a whole new perspective on my life and my future.
                            I especially appreciated the personalized guidance and advice that Onirix provided. It wasn't just a generic report
                            - it felt like the AI really understood me and my unique situation.
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- Single item -->
                <div class="carousel-item">
                  <div class="row d-flex justify-content-center">
                    <div class="col-lg-10 col-xl-8">
                      <div class="row">
                        <div class="col-lg-4 d-flex justify-content-center">
                          <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(9).webp"
                            class="rounded-circle shadow-1 mb-4 mb-lg-0" alt="woman avatar" width="150"
                            height="150" />
                        </div>
                        <div
                          class="col-9 col-md-9 col-lg-7 col-xl-8 text-center text-lg-start text-black mx-auto mx-lg-0">
                          <h4 class="mb-4">Max Doodligan - 30 years old</h4>
                          <p class="mb-0 pb-3">
                            Overall, I would highly recommend Onirix to anyone who is struggling with their relationships or any other personal issues.
                            The AI's ability to decode and analyze dreams is truly remarkable, and it can provide invaluable insights into our own minds and emotions.
                            Thanks to Onirix, I feel like I have a better understanding of myself and my relationships, and I'm better equipped to navigate the ups and downs of life.
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- Carousel wrapper -->
              </div>
              <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>