config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'
  get 'contacts/create'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {}

  root to: "pages#home"
  get "about", to: "pages#about"
  get "contact", to: "contacts#new"
  get "tac", to: "pages#tac"
  get "policies", to: "pages#policies"

  resources :contacts, only: [:new, :create]
  get "blog", to: "pages#blog"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :dreamlogs do
    resources :dreams, only: [:new, :create, :index, :show]
  end

  resources :dreams, only: [:edit, :update, :destroy] do
    resources :interpretations, only: [:new, :create, :index, :show]
    get 'analyze', to: 'interpretations#analyze'
  end
  resources :interpretations, only: [:edit, :update, :destroy]
  resources :personal_details, only: [:create, :edit, :update, :destroy]

  get 'discuss', to: 'interpretations#discuss'
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  skip_before_action :authenticate_user!

  def new
    @contact = Contact.new
  end

  # def create
  #   success = verify_recaptcha(action: 'login', minimum_score: 0.5, secret_key: ENV['RECAPTCHA_SECRET_KEY_V3'])
  #   checkbox_success = verify_recaptcha unless success
  #   if success || checkbox_success
  #     @contact = Contact.new(contact_params)
  #     if @contact.save
  #       redirect_to new_contact_path, notice: "Votre message a été envoyé avec succès."
  #     else
  #       render :new
  #     end
  #   else
  #     if !success
  #       @show_checkbox_recaptcha = true
  #     end
  #     render 'new'
  #   end
  # end
  def create
    success = verify_recaptcha(action: 'login', minimum_score: 0.5, secret_key: ENV['RECAPTCHA_SECRET_KEY_V3'])
    checkbox_success = verify_recaptcha unless success

    if (success || checkbox_success) && (contact = Contact.new(contact_params)).save
      redirect_to new_contact_path, notice: "Your message has been successfully sent."
    else
      @show_checkbox_recaptcha = !success
      render :new
    end
  end



  private

  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end
end

app/views/contacts/new.html.erb
<div class='login-form mt-4'>
  <div class="form-logo">
    <%= image_tag "logo-h-w.svg" %>
  </div>
<h1 class="my-4">Contact us</h1>

  <div class='mt-4'>
    <%= simple_form_for @contact, url: contacts_path do |f| %>
      <%= f.input :name, label: 'Full name' %>
      <%= f.input :email, label: 'Email' %>
      <%= f.input :message, label: 'Message', as: :text %>
      <% if @show_checkbox_recaptcha %>
        <%= recaptcha_tags %>
      <% else %>
        <%= recaptcha_v3(action: 'login', site_key: ENV['RECAPTCHA_SITE_KEY_V3']) %>
      <% end %>
      <%= f.button :submit, 'Send', class: 'btn main-cta-color-BonWup' %>
    <% end %>
  </div>
</div>